import fs from 'fs';
import path from 'path';

// Create dist directory if it doesn't exist
if (!fs.existsSync('dist')) {
  fs.mkdirSync('dist');
}

// Check if the primary declaration file was generated
if (fs.existsSync('dist/index.d.ts')) {
  console.log('✅ TypeScript declarations generated successfully by vite-plugin-dts!');
} else {
  console.warn('⚠️ Warning: dist/index.d.ts was not generated by vite-plugin-dts');
  
  // As a fallback, copy the existing declaration file if available
  if (fs.existsSync('src/types/searchbar.d.ts')) {
    fs.copyFileSync(
      path.resolve('src', 'types', 'searchbar.d.ts'),
      path.resolve('dist', 'index.d.ts')
    );
    console.log('✅ Fallback: Copied src/types/searchbar.d.ts to dist/index.d.ts');
  }
}

// Copy any additional necessary files for the package
console.log('✅ TypeScript declarations process completed!');